### ISSUE TITLE
Why did you use cv2 library

### ISSUE THREAD

**Issue by SAliSH79** [MahdiyehKRM/color-eye-detection-#1]
Hi
Greetings
## Question
I want to understand your code, But I am curious to know why did you import cv2 library?
Does it possess any special built-in function?

**Comment by MahdiyehKRM** [comment]
They generally use the open cv library for image processing
And cv2 is an improved cv, and according to tutorials and people who work in this career, they use cv2.
you can use keras and deep learning too for writing code  but I only use cv2

**Comment by SAliSH79** [comment]
Thanks
